import { Box } from "@mui/material";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import WhatsAppFloating from "./components/whatsapp/Whatsapp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Box
          sx={{
            backgroundColor: "#e6e6e6",
            margin: "0px -8px",
          }}
        >
          <Box sx={{ margin: "0px -10px 20px -8px" }}>
            <Navbar />
          </Box>
          <Box
            sx={{
              minHeight: "100vh",
            }}
          >
            {children}
          </Box>
          <Box sx={{ margin: "0px -10px 20px -8px" }}>
            <Footer />
          </Box>
          <WhatsAppFloating />
        </Box>
      </body>
    </html>
  );
}
